/**
 * Compliance Tagger — IPTC Metadata
 * 
 * IPTC:     Applies trainedAlgorithmicMedia tag to satisfy 2026 transparency laws.
 * 
 * This module handles post-VTO metadata enrichment and compliance flag updates.
 */

export interface ComplianceResult {
    synthidApplied: boolean;
    iptcTagged: boolean;
    iptcMetadata: Record<string, string>;
}

/**
 * IPTC metadata to embed in generated assets.
 * Required for 2026 AI transparency regulations.
 */
const IPTC_AI_METADATA = {
    'Iptc4xmpExt:DigitalImageGUID': '',           // Set per-image
    'Iptc4xmpExt:DigitalSourceType': 'trainedAlgorithmicMedia',
    'dc:creator': 'VideoAd AI Pipeline',
    'dc:rights': 'AI-generated virtual try-on. Original product imagery belongs to respective brands.',
    'photoshop:Credit': 'Generated by Fashn AI tryon v1.6',
    'xmpRights:Marked': 'True',
    'xmpRights:WebStatement': 'https://videoad-mu.vercel.app/ai-disclosure',
};

export class ComplianceTagger {

    /**
     * Tag an asset as compliant.
     * IPTC tags are generated here for storage alongside the asset.
     * 
     * @param assetId - Unique identifier for the asset (e.g., CDN URL or DB ID)
     */
    generateComplianceTags(assetId: string): ComplianceResult {
        const iptcMetadata = {
            ...IPTC_AI_METADATA,
            'Iptc4xmpExt:DigitalImageGUID': assetId,
        };

        return {
            synthidApplied: false,       // Fashn does not use SynthID
            iptcTagged: true,
            iptcMetadata,
        };
    }

    /**
     * Generate EXIF-compatible metadata block for an asset.
     * This can be embedded when the image is served or downloaded.
     */
    generateExifBlock(assetId: string, brand: string, productTitle: string): Record<string, string> {
        return {
            'ImageDescription': `AI Virtual Try-On: ${productTitle} by ${brand}`,
            'Software': 'Fashn AI tryon v1.6',
            'Artist': 'VideoAd AI Pipeline',
            'Copyright': `Original product: ${brand}. AI render: VideoAd. 2026.`,
            'UserComment': `DigitalSourceType: trainedAlgorithmicMedia | AssetID: ${assetId}`,
        };
    }
}

export const complianceTagger = new ComplianceTagger();
